analyzer:
  errors:
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    unused_import: ignore
    unused_element: ignore
    dead_code: ignore
    prefer_const_declarations: ignore
    prefer_const_constructors: ignore
    no_leading_underscores_for_local_identifiers: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_import: ignore
